/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import code.CProductos;
import java.awt.Frame;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author luism
 */
public class EditarProductos extends javax.swing.JDialog {

    private int idProductoSeleccionado;
    private JTable tbProductos;
    
    

    /**
     *
     * @param id
     */
    
    public void setIdProductoSeleccionado(int id) {
        this.idProductoSeleccionado = id;
    }
    /**
     * Creates new form AgregarProducto
     */
    //Instanciamos el fondo de pantalla para que en el construct lo mostremos
    Background fondo = new Background();
    public EditarProductos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setContentPane(fondo);
        initComponents();
    }

     public EditarProductos(Frame parent, boolean modal, JTable tbProductos) {
        super(parent, modal);
        initComponents();
        this.tbProductos = tbProductos;  // Guarda la referencia de la tabla
    }
     
      public void setCodigo(String codigo) {
        txtCodigo.setText(codigo);
    }

    public void setNombre(String nombre) {
        txtNombre.setText(nombre);
    }

    public void setPrecio(String precio) {
        txtPrecio.setText(precio);
    }

    public void setExistencia(String existencia) {
        txtExistencia.setText(existencia);
    }

    public void setCategoria(String categoria) {
        txtCategoria.setText(categoria);
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgUsers = new javax.swing.JLabel();
        imgUser1 = new javax.swing.JLabel();
        bgEditProduct = new Background();
        bgForm = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtExistencia = new javax.swing.JTextField();
        txtCategoria = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        imgUser2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtPrecio = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();
        imgUsers1 = new javax.swing.JLabel();

        imgUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editUser.png"))); // NOI18N
        imgUsers.setText("jLabel1");

        imgUser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgEditProduct.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgForm.setBackground(new java.awt.Color(255, 255, 255));
        bgForm.setForeground(new java.awt.Color(255, 255, 255));
        bgForm.setPreferredSize(new java.awt.Dimension(550, 600));
        bgForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Editar Producto");
        bgForm.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));
        bgForm.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 320, 40));
        bgForm.add(txtExistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 320, 40));
        bgForm.add(txtCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 320, 40));
        bgForm.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 320, 40));

        btnModificar.setBackground(new java.awt.Color(89, 131, 252));
        btnModificar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editPackage.png"))); // NOI18N
        btnModificar.setText("Editar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        bgForm.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 120, 40));

        imgUser2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editPackage.png"))); // NOI18N
        bgForm.add(imgUser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(143, 142, 142));
        jLabel7.setText("Codigo");
        bgForm.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 60, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(143, 142, 142));
        jLabel1.setText("Nombre");
        bgForm.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 64, 18));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(143, 142, 142));
        jLabel2.setText("Precio");
        bgForm.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 46, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(143, 142, 142));
        jLabel3.setText("Existencia");
        bgForm.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, 18));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(143, 142, 142));
        jLabel4.setText("Categoria");
        bgForm.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, 18));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        bgForm.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 54, 220, 10));
        bgForm.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 320, 40));

        btnExit.setBackground(new java.awt.Color(234, 67, 53));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconExit.png"))); // NOI18N
        btnExit.setText("Cancelar");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        bgForm.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 120, 40));

        bgEditProduct.add(bgForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 431, 488));

        imgUsers1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/EditProduct.png"))); // NOI18N
        imgUsers1.setText("jLabel1");
        bgEditProduct.add(imgUsers1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 280, 210));

        getContentPane().add(bgEditProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // Agregar a la BD

        CProductos objetoProductos = new CProductos();
        objetoProductos.EditarProducto(idProductoSeleccionado, txtCodigo, txtNombre, txtPrecio, txtExistencia, txtCategoria);
        dispose();
        objetoProductos.MostrarProductos(tbProductos);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditarProductos dialog = new EditarProductos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    class Background extends JPanel {

        private Image imagen;

        @Override
        public void paintComponent(Graphics g) {
            super.paintComponent(g);
            imagen = new ImageIcon(getClass().getResource("/img/bgAgregarUsuarios.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgEditProduct;
    private javax.swing.JPanel bgForm;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel imgUser1;
    private javax.swing.JLabel imgUser2;
    private javax.swing.JLabel imgUsers;
    private javax.swing.JLabel imgUsers1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtExistencia;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
