/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import code.CVentas;
import code.GeneradorPDF;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author luism
 */
public class Ventas extends javax.swing.JPanel {
DefaultTableModel modeloCarrito;

    /**
     * Creates new form Ventas
     */
    public Ventas() {
        initComponents();
          // Configurar el modelo de la tabla
    modeloCarrito = new DefaultTableModel();
    modeloCarrito.addColumn("Código");
    modeloCarrito.addColumn("Nombre");
    modeloCarrito.addColumn("Precio");
    modeloCarrito.addColumn("Cantidad");
    modeloCarrito.addColumn("Total");
    
    
    // Asignar el modelo a la tabla
    tbCarrito.setModel(modeloCarrito);
    
    tbCarrito.getSelectionModel().addListSelectionListener(e -> {
    // Habilita el botón solo si hay una fila seleccionada
    btnClear.setEnabled(!tbCarrito.getSelectionModel().isSelectionEmpty());
    });
    
    btnClear.setEnabled(false); //el Boton empieza deshabilitado
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new Background();
        jLabel5 = new javax.swing.JLabel();
        txtProductoVenta = new javax.swing.JTextField();
        txtCantidadVenta = new javax.swing.JTextField();
        txtPrecioVenta = new javax.swing.JTextField();
        txtExistenciaVenta = new javax.swing.JTextField();
        txtCodigoVenta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCarrito = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        txtNITCliente = new javax.swing.JTextField();
        txtDireccionCliente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnFin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        setPreferredSize(new java.awt.Dimension(880, 470));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(880, 470));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Cantidad:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        txtProductoVenta.setEditable(false);
        txtProductoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductoVentaActionPerformed(evt);
            }
        });
        jPanel1.add(txtProductoVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 167, 31));

        txtCantidadVenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCantidadVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadVentaActionPerformed(evt);
            }
        });
        jPanel1.add(txtCantidadVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 90, 40));

        txtPrecioVenta.setEditable(false);
        txtPrecioVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioVentaActionPerformed(evt);
            }
        });
        jPanel1.add(txtPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 90, 31));

        txtExistenciaVenta.setEditable(false);
        txtExistenciaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExistenciaVentaActionPerformed(evt);
            }
        });
        jPanel1.add(txtExistenciaVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, 90, 31));

        txtCodigoVenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCodigoVenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCodigoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoVentaActionPerformed(evt);
            }
        });
        jPanel1.add(txtCodigoVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 84, 190, 40));

        tbCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbCarrito);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 169, 790, 300));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Total:      Q");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 475, -1, 26));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel9.setText("Ingreso de producto:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 38, 200, -1));

        txtNombreCliente.setForeground(new java.awt.Color(204, 204, 204));
        txtNombreCliente.setText("Nombre...");
        txtNombreCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNombreCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreClienteMousePressed(evt);
            }
        });
        txtNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreClienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 160, 31));

        txtTotal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTotal.setBorder(null);
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 96, 26));

        txtNITCliente.setForeground(new java.awt.Color(204, 204, 204));
        txtNITCliente.setText("C/F");
        txtNITCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNITCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNITClienteMousePressed(evt);
            }
        });
        txtNITCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNITClienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtNITCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 130, 31));

        txtDireccionCliente.setForeground(new java.awt.Color(204, 204, 204));
        txtDireccionCliente.setText("Direccion...");
        txtDireccionCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDireccionCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDireccionClienteMousePressed(evt);
            }
        });
        txtDireccionCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionClienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtDireccionCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 130, 140, 33));

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel10.setText("Informacion del Cliente:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 200, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Codigo:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel11.setText("Detalles del producto:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 200, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Producto:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("Existencia:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, -1, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setText("Precio:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, -1, -1));

        btnReset.setBackground(new java.awt.Color(89, 131, 252));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/resetIcon.png"))); // NOI18N
        btnReset.setText("Deshacer");
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, 33));

        btnClear.setBackground(new java.awt.Color(234, 67, 53));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconDelete.png"))); // NOI18N
        btnClear.setText("Limpiar");
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 100, 33));

        btnAdd.setBackground(new java.awt.Color(52, 168, 83));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/addIcon.png"))); // NOI18N
        btnAdd.setText("Agregar");
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 130, -1, 33));

        btnFin.setBackground(new java.awt.Color(89, 131, 252));
        btnFin.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnFin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/doneIcon.png"))); // NOI18N
        btnFin.setText("Finalizar");
        btnFin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinActionPerformed(evt);
            }
        });
        jPanel1.add(btnFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 110, 36));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Nueva Venta");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 0, 144, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/listIcon.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 2, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtProductoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductoVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductoVentaActionPerformed

    private void txtCantidadVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadVentaActionPerformed

    private void txtPrecioVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioVentaActionPerformed

    private void txtExistenciaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExistenciaVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExistenciaVentaActionPerformed

    private void txtCodigoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoVentaActionPerformed
        // una vez puesto el codigo, busca los valores asociados y los muestra en los txt                                              
    String codigoProducto = txtCodigoVenta.getText();
    if (!codigoProducto.isEmpty()) {
        CVentas venta = new CVentas();
        ResultSet rs = venta.buscarProductoPorCodigo(codigoProducto);
        
          try {
                if (rs != null && rs.next()) {  // Si se encuentra el producto
                    txtProductoVenta.setText(rs.getString("nombre"));
                    txtPrecioVenta.setText(rs.getString("precio"));
                    txtExistenciaVenta.setText(rs.getString("existencia"));
                } else {
                    JOptionPane.showMessageDialog(null, "Producto no encontrado.");
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error al buscar el producto.");
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, ingresa un código.");
        }
    
        
        
        
    }//GEN-LAST:event_txtCodigoVentaActionPerformed

    private void txtNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreClienteActionPerformed

    private void txtNITClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNITClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNITClienteActionPerformed

    private void txtDireccionClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionClienteActionPerformed

    private void txtNombreClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreClienteMousePressed
        //Ser fancy, permite que el campo tenga un mensaje y se quite al escribir
        if (txtNombreCliente.getText().equals("Nombre...")){
        txtNombreCliente.setText("");
        txtNombreCliente.setForeground(Color.black);
        }
        
        if (txtDireccionCliente.getText().equals("")){
            txtDireccionCliente.setText("Direccion...");
            txtDireccionCliente.setForeground(Color.gray);
        }
        
        if (txtNITCliente.getText().equals("")){
            txtNITCliente.setText("C/F");
            txtNITCliente.setForeground(Color.gray);
        }
        
    }//GEN-LAST:event_txtNombreClienteMousePressed

    private void txtNITClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNITClienteMousePressed
        
        if (txtNITCliente.getText().equals("C/F")){
        txtNITCliente.setText("");
        txtNITCliente.setForeground(Color.black);
        }
        
        if (txtDireccionCliente.getText().equals("")){
            txtDireccionCliente.setText("Direccion...");
            txtDireccionCliente.setForeground(Color.gray);
        }
        
        if (txtNombreCliente.getText().equals("")){
            txtNombreCliente.setText("Nombre...");
            txtNombreCliente.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtNITClienteMousePressed

    private void txtDireccionClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDireccionClienteMousePressed
        
        if (txtDireccionCliente.getText().equals("Direccion...")){
        txtDireccionCliente.setText("");
        txtDireccionCliente.setForeground(Color.black);
        }
        
        if (txtNITCliente.getText().equals("")){
            txtNITCliente.setText("C/F");
            txtNITCliente.setForeground(Color.gray);
        }
        
        if (txtNombreCliente.getText().equals("")){
            txtNombreCliente.setText("Nombre...");
            txtNombreCliente.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtDireccionClienteMousePressed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
    // Permite eliminar la fila seleccionada del carrito
    CVentas ventas = new CVentas();
    int filaSeleccionada = tbCarrito.getSelectedRow();  // Obtener la fila seleccionada

    if (filaSeleccionada >= 0) {
        boolean confirmado = ventas.Confirmacion(
                "¿Estás seguro de que deseas eliminar este producto del carrito?", 
                "Confirmar Eliminación"
        );
     if (confirmado){   
        DefaultTableModel model = (DefaultTableModel) tbCarrito.getModel();
        model.removeRow(filaSeleccionada);  // Eliminar la fila seleccionada
        JOptionPane.showMessageDialog(null, "Producto eliminado del carrito.");
        txtTotal.setText(String.valueOf(ventas.actualizarTotal(tbCarrito)));; //Actualiza nuevo total
     }
      } else {
        JOptionPane.showMessageDialog(null, "Por favor, selecciona un producto para eliminar.");
    }
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtCodigoVenta.setText("");
        txtProductoVenta.setText("");
        txtCantidadVenta.setText("");
        txtExistenciaVenta.setText("");
        txtPrecioVenta.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // Agregar a tabla y valida que la cantidad no exceda a la Existencia
         try {
              if (txtExistenciaVenta.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese el Codigo de Producto antes de Continuar");
            return;  // Detener la ejecución si está vacío
        }
            int cantidadIngresada = Integer.parseInt(txtCantidadVenta.getText());  // Obtener cantidad
            int existenciaProducto = Integer.parseInt(txtExistenciaVenta.getText()); // Obtener Existencia
                       
            if (cantidadIngresada > existenciaProducto) {  // Validar existencia
                JOptionPane.showMessageDialog(null, "La cantidad ingresada excede la existencia disponible.");
            } else {
                //------Inicia Codigo que agrega Producto a la tabla------
                try {
        
        
        if (txtCantidadVenta.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, ingresa una cantidad.");
            return;  
        }
      
        if (cantidadIngresada > existenciaProducto) {
            JOptionPane.showMessageDialog(null, "La cantidad ingresada excede la existencia.");
            return;
        }

        // Obtener los valores del producto
        String codigo = txtCodigoVenta.getText();
        String nombre = txtProductoVenta.getText();
        float precio = Float.parseFloat(txtPrecioVenta.getText()); //float en vez de DOUBLE temporal, para probar
        float total = precio * cantidadIngresada;
        total = Math.round(total * 100) / 100.0f; // Redondea a dos decimales
        // Agregar la fila a la tabla (carrito)
        Object[] fila = {codigo, nombre, precio, cantidadIngresada, total};
        modeloCarrito.addRow(fila);

        //JOptionPane.showMessageDialog(null, "Producto agregado al carrito."); //Molesto, regresar si necesario
        //Vaciar Campos
        txtCodigoVenta.setText("");
        txtProductoVenta.setText("");
        txtPrecioVenta.setText("");
        txtExistenciaVenta.setText("");
        txtCantidadVenta.setText("");
        
        CVentas ventas = new CVentas(); //Crea objeto y usa funcion para actualizar el total      
        txtTotal.setText(String.valueOf(ventas.actualizarTotal(tbCarrito))); //Copiar y pegar cada que se quiera actualizar total

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Por favor, ingresa valores numéricos válidos.");
    }
                //------Finaliza Codigo que agrega Producto a la tabla------
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Por favor, ingresa una cantidad válida.");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinActionPerformed
        CVentas ventas = new CVentas();
         
        String nombreCliente = txtNombreCliente.getText();
        String DireccionCliente = txtDireccionCliente.getText();
        String nitCliente = txtNITCliente.getText();
        Float TotalDeVenta = Float.parseFloat(txtTotal.getText());
         // Verificar si la tabla del carrito está vacía
    if (tbCarrito.getRowCount() == 0) {
        JOptionPane.showMessageDialog(null, "El carrito está vacío. Agrega productos antes de confirmar la venta.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return; // Salir del método si la tabla está vacía
    }
        // Funcion para ver que los campos esten distitnos que la template
    if (txtNombreCliente.getText().equals("Nombre...") ||  txtDireccionCliente.getText().equals("Direccion...")){
        JOptionPane.showMessageDialog(null, "Complete los campos del Cliente antes de continuar", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }  
      
         if (!ventas.validarDatosCliente(nombreCliente, txtNITCliente, DireccionCliente)) {
        return; // Salir si la validación falla
    } 
         
        ventas.confirmarVenta(nombreCliente, tbCarrito, TotalDeVenta, nitCliente);
    //funcion ubicada en clase CVentas que hace la consulta a BD para eliminar existencias    
    //Tambien hace que se guarden los datos de la compra en tabla facturas    
        
    // Crear el PDF de la factura
    GeneradorPDF generador = new GeneradorPDF();
    try {
        generador.crearFactura(nombreCliente, nitCliente, DireccionCliente, tbCarrito, TotalDeVenta);
    } catch (IOException ex) {
        Logger.getLogger(Ventas.class.getName()).log(Level.SEVERE, null, ex);
    }

    // Mensaje de éxito (quizas quitar para version final)
        System.out.println("Venta Completada y Factura Generada");
    
    //Regresar Campos a Vacio
        txtCodigoVenta.setText("");
        txtProductoVenta.setText("");
        txtCantidadVenta.setText("");
        txtExistenciaVenta.setText("");
        txtPrecioVenta.setText("");
        txtNombreCliente.setText("");
        txtNITCliente.setText("");
        txtDireccionCliente.setText("");
        txtTotal.setText("");
        DefaultTableModel modelo = (DefaultTableModel) tbCarrito.getModel();
        modelo.setRowCount(0); //Vaciar tabla
    }//GEN-LAST:event_btnFinActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed
    class Background extends JPanel{
        private Image imagen;
        
        public void paint (Graphics g){
            imagen = new ImageIcon(getClass().getResource("/img/bgContent.png")).getImage();
            g.drawImage(imagen, 0, 0,getWidth(),getHeight(),this);
            setOpaque(false);
            super.paint(g);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnFin;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbCarrito;
    private javax.swing.JTextField txtCantidadVenta;
    private javax.swing.JTextField txtCodigoVenta;
    private javax.swing.JTextField txtDireccionCliente;
    private javax.swing.JTextField txtExistenciaVenta;
    private javax.swing.JTextField txtNITCliente;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtPrecioVenta;
    private javax.swing.JTextField txtProductoVenta;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
