/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import code.CVentas;
import code.GeneradorPDF;
import java.awt.Color;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author luism
 */
public class Ventas extends javax.swing.JPanel {
DefaultTableModel modeloCarrito;

    /**
     * Creates new form Ventas
     */
    public Ventas() {
        initComponents();
          // Configurar el modelo de la tabla
    modeloCarrito = new DefaultTableModel();
    modeloCarrito.addColumn("Código");
    modeloCarrito.addColumn("Nombre");
    modeloCarrito.addColumn("Precio");
    modeloCarrito.addColumn("Cantidad");
    modeloCarrito.addColumn("Total");
    
    
    // Asignar el modelo a la tabla
    tbCarrito.setModel(modeloCarrito);
    
    tbCarrito.getSelectionModel().addListSelectionListener(e -> {
    // Habilita el botón solo si hay una fila seleccionada
    btnEliminarCarrito.setEnabled(!tbCarrito.getSelectionModel().isSelectionEmpty());
    });
    
    btnEliminarCarrito.setEnabled(false); //el Boton empieza deshabilitado
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtProductoVenta = new javax.swing.JTextField();
        txtCantidadVenta = new javax.swing.JTextField();
        txtPrecioVenta = new javax.swing.JTextField();
        txtExistenciaVenta = new javax.swing.JTextField();
        txtCodigoVenta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCarrito = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btnCompletar = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtNITCliente = new javax.swing.JTextField();
        txtDireccionCliente = new javax.swing.JTextField();
        btnEliminarCarrito = new javax.swing.JLabel();

        setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        setPreferredSize(new java.awt.Dimension(880, 470));

        jPanel1.setBackground(new java.awt.Color(0,0,0,0));
        jPanel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(880, 470));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Producto:");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Cantidad:");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Precio:");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setText("Existencia:");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setText("Codigo:");

        txtProductoVenta.setEditable(false);
        txtProductoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductoVentaActionPerformed(evt);
            }
        });

        txtCantidadVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadVentaActionPerformed(evt);
            }
        });

        txtPrecioVenta.setEditable(false);
        txtPrecioVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioVentaActionPerformed(evt);
            }
        });

        txtExistenciaVenta.setEditable(false);
        txtExistenciaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExistenciaVentaActionPerformed(evt);
            }
        });

        txtCodigoVenta.setBorder(null);
        txtCodigoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoVentaActionPerformed(evt);
            }
        });

        tbCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbCarrito);

        jLabel6.setText("Total:      Q");

        btnCompletar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnCompletar.setText("Completar");
        btnCompletar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCompletarMouseClicked(evt);
            }
        });

        btnAgregar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel9.setText("Informacion del Cliente:");

        txtNombreCliente.setForeground(new java.awt.Color(204, 204, 204));
        txtNombreCliente.setText("Nombre...");
        txtNombreCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreClienteMousePressed(evt);
            }
        });
        txtNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreClienteActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setText("Limpiar");

        txtTotal.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTotal.setBorder(null);

        txtNITCliente.setForeground(new java.awt.Color(204, 204, 204));
        txtNITCliente.setText("NIT...");
        txtNITCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNITClienteMousePressed(evt);
            }
        });
        txtNITCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNITClienteActionPerformed(evt);
            }
        });

        txtDireccionCliente.setForeground(new java.awt.Color(204, 204, 204));
        txtDireccionCliente.setText("Direccion...");
        txtDireccionCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDireccionClienteMousePressed(evt);
            }
        });
        txtDireccionCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionClienteActionPerformed(evt);
            }
        });

        btnEliminarCarrito.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnEliminarCarrito.setText("Deshacer");
        btnEliminarCarrito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarCarritoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCodigoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtProductoVenta)
                        .addGap(18, 18, 18)
                        .addComponent(txtCantidadVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel2)))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtExistenciaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar))
                .addGap(18, 18, 18)
                .addComponent(btnEliminarCarrito)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(447, 447, 447)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtNITCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtDireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(235, 235, 235)
                                .addComponent(btnCompletar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 31, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEliminarCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProductoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidadVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtExistenciaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCompletar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNITCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtProductoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductoVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductoVentaActionPerformed

    private void txtCantidadVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadVentaActionPerformed

    private void txtPrecioVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioVentaActionPerformed

    private void txtExistenciaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExistenciaVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExistenciaVentaActionPerformed

    private void txtCodigoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoVentaActionPerformed
        // una vez puesto el codigo, busca los valores asociados y los muestra en los txt                                              
    String codigoProducto = txtCodigoVenta.getText();
    if (!codigoProducto.isEmpty()) {
        CVentas venta = new CVentas();
        ResultSet rs = venta.buscarProductoPorCodigo(codigoProducto);
        
          try {
                if (rs != null && rs.next()) {  // Si se encuentra el producto
                    txtProductoVenta.setText(rs.getString("nombre"));
                    txtPrecioVenta.setText(rs.getString("precio"));
                    txtExistenciaVenta.setText(rs.getString("existencia"));
                } else {
                    JOptionPane.showMessageDialog(null, "Producto no encontrado.");
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error al buscar el producto.");
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, ingresa un código.");
        }
    
        
        
        
    }//GEN-LAST:event_txtCodigoVentaActionPerformed

    private void txtNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreClienteActionPerformed

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        // Agregar a tabla y valida que la cantidad no exceda a la Existencia
         try {
              if (txtExistenciaVenta.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese el Codigo de Producto antes de Continuar");
            return;  // Detener la ejecución si está vacío
        }
            int cantidadIngresada = Integer.parseInt(txtCantidadVenta.getText());  // Obtener cantidad
            int existenciaProducto = Integer.parseInt(txtExistenciaVenta.getText()); // Obtener Existencia
                       
            if (cantidadIngresada > existenciaProducto) {  // Validar existencia
                JOptionPane.showMessageDialog(null, "La cantidad ingresada excede la existencia disponible.");
            } else {
                //------Inicia Codigo que agrega Producto a la tabla------
                try {
        
        
        if (txtCantidadVenta.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, ingresa una cantidad.");
            return;  
        }
      
        if (cantidadIngresada > existenciaProducto) {
            JOptionPane.showMessageDialog(null, "La cantidad ingresada excede la existencia.");
            return;
        }

        // Obtener los valores del producto
        String codigo = txtCodigoVenta.getText();
        String nombre = txtProductoVenta.getText();
        float precio = Float.parseFloat(txtPrecioVenta.getText()); //float en vez de DOUBLE temporal, para probar
        float total = precio * cantidadIngresada;
        total = Math.round(total * 100) / 100.0f; // Redondea a dos decimales
        // Agregar la fila a la tabla (carrito)
        Object[] fila = {codigo, nombre, precio, cantidadIngresada, total};
        modeloCarrito.addRow(fila);

        JOptionPane.showMessageDialog(null, "Producto agregado al carrito.");
        //Vaciar Campos
        txtCodigoVenta.setText("");
        txtProductoVenta.setText("");
        txtPrecioVenta.setText("");
        txtExistenciaVenta.setText("");
        txtCantidadVenta.setText("");
        
        CVentas ventas = new CVentas(); //Crea objeto y usa funcion para actualizar el total      
        txtTotal.setText(String.valueOf(ventas.actualizarTotal(tbCarrito))); //Copiar y pegar cada que se quiera actualizar total

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Por favor, ingresa valores numéricos válidos.");
    }
                //------Finaliza Codigo que agrega Producto a la tabla------
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Por favor, ingresa una cantidad válida.");
        }
    
    }//GEN-LAST:event_btnAgregarMouseClicked

    private void btnCompletarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCompletarMouseClicked
        CVentas ventas = new CVentas();
         
        String nombreCliente = txtNombreCliente.getText();
        String DireccionCliente = txtDireccionCliente.getText();
        String nitCliente = txtNITCliente.getText();
        Float TotalDeVenta = Float.parseFloat(txtTotal.getText());
         // Verificar si la tabla del carrito está vacía
    if (tbCarrito.getRowCount() == 0) {
        JOptionPane.showMessageDialog(null, "El carrito está vacío. Agrega productos antes de confirmar la venta.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return; // Salir del método si la tabla está vacía
    }
        // Funcion para ver que los campos esten distitnos que la template
    if (txtNombreCliente.getText().equals("Nombre...") || txtNITCliente.getText().equals("NIT...") || txtDireccionCliente.getText().equals("Direccion...")){
        JOptionPane.showMessageDialog(null, "Complete los campos del Cliente antes de continuar", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }  
      
         if (!ventas.validarDatosCliente(nombreCliente, txtNITCliente, DireccionCliente)) {
        return; // Salir si la validación falla
    } 
         
        ventas.confirmarVenta(tbCarrito); //funcion ubicada en clase CVentas que hace la consulta a BD para eliminar existencias
    // Crear el PDF de la factura
    GeneradorPDF generador = new GeneradorPDF();
    try {
        generador.crearFactura(nombreCliente, nitCliente, DireccionCliente, tbCarrito, TotalDeVenta);
    } catch (IOException ex) {
        Logger.getLogger(Ventas.class.getName()).log(Level.SEVERE, null, ex);
    }

    // Mensaje de éxito
    JOptionPane.showMessageDialog(null, "Venta completada y factura generada.");

    }//GEN-LAST:event_btnCompletarMouseClicked

    private void txtNITClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNITClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNITClienteActionPerformed

    private void txtDireccionClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionClienteActionPerformed

    private void txtNombreClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreClienteMousePressed
        //Ser fancy, permite que el campo tenga un mensaje y se quite al escribir
        if (txtNombreCliente.getText().equals("Nombre...")){
        txtNombreCliente.setText("");
        txtNombreCliente.setForeground(Color.black);
        }
        
        if (txtDireccionCliente.getText().equals("")){
            txtDireccionCliente.setText("Direccion...");
            txtDireccionCliente.setForeground(Color.gray);
        }
        
        if (txtNITCliente.getText().equals("")){
            txtNITCliente.setText("NIT...");
            txtNITCliente.setForeground(Color.gray);
        }
        
    }//GEN-LAST:event_txtNombreClienteMousePressed

    private void txtNITClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNITClienteMousePressed
        
        if (txtNITCliente.getText().equals("NIT...")){
        txtNITCliente.setText("");
        txtNITCliente.setForeground(Color.black);
        }
        
        if (txtDireccionCliente.getText().equals("")){
            txtDireccionCliente.setText("Direccion...");
            txtDireccionCliente.setForeground(Color.gray);
        }
        
        if (txtNombreCliente.getText().equals("")){
            txtNombreCliente.setText("Nombre...");
            txtNombreCliente.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtNITClienteMousePressed

    private void txtDireccionClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDireccionClienteMousePressed
        
        if (txtDireccionCliente.getText().equals("Direccion...")){
        txtDireccionCliente.setText("");
        txtDireccionCliente.setForeground(Color.black);
        }
        
        if (txtNITCliente.getText().equals("")){
            txtNITCliente.setText("NIT...");
            txtNITCliente.setForeground(Color.gray);
        }
        
        if (txtNombreCliente.getText().equals("")){
            txtNombreCliente.setText("Nombre...");
            txtNombreCliente.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtDireccionClienteMousePressed

    private void btnEliminarCarritoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarCarritoMouseClicked
        // Permite eliminar la fila seleccionada del carrito
        CVentas ventas = new CVentas();
          int filaSeleccionada = tbCarrito.getSelectedRow();  // Obtener la fila seleccionada

    if (filaSeleccionada >= 0) {
        boolean confirmado = ventas.Confirmacion(
                "¿Estás seguro de que deseas eliminar este producto del carrito?", 
                "Confirmar Eliminación"
        );
     if (confirmado){   
        DefaultTableModel model = (DefaultTableModel) tbCarrito.getModel();
        model.removeRow(filaSeleccionada);  // Eliminar la fila seleccionada
        JOptionPane.showMessageDialog(null, "Producto eliminado del carrito.");
        txtTotal.setText(String.valueOf(ventas.actualizarTotal(tbCarrito)));; //Actualiza nuevo total
     }
      } else {
        JOptionPane.showMessageDialog(null, "Por favor, selecciona un producto para eliminar.");
    }
         
    
    }//GEN-LAST:event_btnEliminarCarritoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAgregar;
    private javax.swing.JLabel btnCompletar;
    private javax.swing.JLabel btnEliminarCarrito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbCarrito;
    private javax.swing.JTextField txtCantidadVenta;
    private javax.swing.JTextField txtCodigoVenta;
    private javax.swing.JTextField txtDireccionCliente;
    private javax.swing.JTextField txtExistenciaVenta;
    private javax.swing.JTextField txtNITCliente;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtPrecioVenta;
    private javax.swing.JTextField txtProductoVenta;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
